import React from 'react';
import { ArgsProps } from './svgArgs';
function SvgComponent({ qrcode, title, qrcodeHash, uploadedCid, ...other }: ArgsProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 725 438"
      {...other}
    >
      <foreignObject x="0" y="0" width="725" height="438">
        <img src="\static\mock-images\bg_svgs\bg_svg5.png" alt="backgound" />
      </foreignObject>
      <foreignObject x="200" y="30" width="500" height="70">
        <div
          style={{
            display: 'flex',
            width: '100%',
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            fontFamily: 'Open Sans, sans-serif',
            fontSize: '22px',
            fontWeight: 'bold'
          }}
        >
          {title === '' || undefined ? 'Your title' : title}
        </div>
      </foreignObject>
      <foreignObject x="200" y="350" width="500" height="25">
        <div
          style={{
            display: 'flex',
            width: '100%',
            height: '100%',
            alignItems: 'center',
            justifyContent: 'center',
            textJustify: 'inter-word'
          }}
        >
          <p
            style={{
              textAlign: 'center',
              wordWrap: 'break-word',
              wordBreak: 'break-all',
              textAlignLast: 'center',
              fontFamily: 'Open Sans, sans-serif',
              fontSize: '14px'
            }}
          >
            {uploadedCid.cid}
          </p>
        </div>
      </foreignObject>
      <text x="367" y="391" width="270" height="30" fontSize="9px">
        This NFT is generated by smart contract
      </text>
      <text x="342" y="406" width="270" height="30" fontSize="9px">
        0xa0Afb3513B99E1b099CE9F3C007eE937B04e7870
      </text>
      <text transform="rotate(-90) translate(-280 230)" fontSize="14px" letterSpacing=".3em">
        {'IDENTITY'}
      </text>
      <text transform="rotate(-90) translate(-305 480)" fontSize="14px" letterSpacing=".3em">
        {'REGISTRATION'}
      </text>

      <foreignObject x="190" y="110" width="250" height="250">
        {qrcode}
      </foreignObject>
      <foreignObject x="440" y="110" width="250" height="250">
        {qrcodeHash}
      </foreignObject>
    </svg>
  );
}
const MemoSvgComponent = React.memo(SvgComponent);
export default MemoSvgComponent;
